### ISSUE TITLE
Instructions as give fail

### ISSUE THREAD

**Issue by hsmyers** [lichess-org/api-demo#2]
Upfront I will grant the possibility that I don't know what I'm doing… That said, here is what I did:

```
C:\Users\hsmyers>mkdir Lichess

C:\Users\hsmyers>cd Lichess

C:\Users\hsmyers\Lichess>npm install
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\hsmyers\Lichess\package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\hsmyers\Lichess\package.json'
npm WARN Lichess No description
npm WARN Lichess No repository field.
npm WARN Lichess No README data
npm WARN Lichess No license field.

up to date in 0.334s
found 0 vulnerabilities

```
Starting with the first warning, I deleted the lock file and copied the package.json file from this site to my machine and got this:

```
C:\Users\hsmyers\Lichess>npm install
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules\rollup\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN bootstrap@5.2.2 requires a peer of @popperjs/core@^2.11.6 but none is installed. You must install peer dependencies yourself.

added 133 packages from 166 contributors and audited 134 packages in 64.788s

22 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

I assumed I could survive the first two warnings (marked optional as they are) but had my doubts about the 'install peer dependencies remark. but to confirm, I went ahead and:

```
C:\Users\hsmyers\Lichess>npm run build

> lichess-oauth-app-example@ build C:\Users\hsmyers\Lichess
> rollup --config

[!] Error: Could not resolve entry module (rollup.config.js).
Error: Could not resolve entry module (rollup.config.js).
    at error (C:\Users\hsmyers\Lichess\node_modules\rollup\dist\shared\rollup.js:198:30)
    at ModuleLoader.loadEntryModule (C:\Users\hsmyers\Lichess\node_modules\rollup\dist\shared\rollup.js:22306:20)
    at async Promise.all (index 0)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lichess-oauth-app-example@ build: `rollup --config`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lichess-oauth-app-example@ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hsmyers\AppData\Roaming\npm-cache\_logs\2022-11-17T00_16_59_407Z-debug.log
```

I believe all of this is a cascade from an improper beginning. So what do I need for a warning and error-free run? Thanks!

--hsm

**Comment by ornicar** [comment]
I don't think this has anything to do with Lichess, since your problems start when you do:

```
C:\Users\hsmyers>mkdir Lichess
C:\Users\hsmyers>cd Lichess
C:\Users\hsmyers\Lichess>npm install
```

At this point no lichess code was involved (despite you calling your new dir "Lichess") so this is not the right place to ask.

**Comment by hsmyers** [comment]
Much thanks! I've since determined that my approach was indeed wrong-headed…

--hsm
